<?php

return [
    'Guest',
    'Regional/Central Office',
    'OSDS/SDS Office',
    'OSDS/ASDS Office',
    'OSDS/Admin Office',
    'OSDS/Accounting Office',
    'OSDS/Legal Unit',
    'OSDS/ICT Unit',
    'SGOD Office',
    'CID Office',
    'CID/LRMDS Office',
    'BAC Secretariat',
    'School Personnel Group',
    'Admin/Records Office',
    'Admin/Supply Office',
    'Admin/Cashiering Office',
    'Admin/Personnel',
    'SGOD/M & E',
    'SGOD/Planning',
    'SGOD/SocMob',
    'SGOD/HRLD',
    'SGOD/Health & Nutrition',
    'SGOD/Youth Formation',
    'SGOD/Educational Facilities',
    'SGOD/Budget Office',
    'CID/ALS',
];
